image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      cat <<EOF > .env
      JWT_SECRET=${JWT_SECRET}
      JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      DB_HOST=db
      DB_USER=root
      DB_PORT=3306
      DB_PASSWORD=password
      DB_NAME=task_system
      MYSQL_ROOT_PASSWORD=password
      MYSQL_DATABASE=task_system
      REDIS_HOST=redis
      REDIS_PORT=6379
      EOF
      npm install
      docker-compose down -v
      docker-compose up -d --build
      docker exec -it task_system_api npm install
    command: sleep infinity

ports:
  - port: 3000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 6379
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
