apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: task-system
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: itsadrianapaiva/task-management-api:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: task-system-config
        - secretRef:
            name: task-system-secrets
