openapi: 3.1.0
info:
  title: Task Management API
  description: Role-based task management API for technicians and managers.
  version: 1.0.0

servers:
  - url: http://localhost:3001/api/v1
    description: Local development

tags:
  - name: Auth
    description: Authentication Endpoints
  - name: Tasks
    description: Task Management Endpoints

paths:
  /auth/signup:
    post:
      tags:
        - Auth
      summary: User Signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [manager, technician]
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input data
        '409':
          description: Email already exists
        '500':
          description: Server error

  /auth/login:
    post:
      tags:
        - Auth
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful, JWT returned via cookie
        '400':
          description: Invalid credentials
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /auth/profile:
    get:
      tags:
        - Auth
      summary: Get current user profile
      responses:
        '200':
          description: Current user information
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /tasks:
    post:
      tags:
        - Tasks
      summary: Create a task (Technician only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                performedAt:
                  type: string
                  format: date-time
      responses:
        '201':
          description: Task created successfully
        '400':
          description: Invalid task input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (Technician only)
        '500':
          description: Server error

    get:
      tags:
        - Tasks
      summary: Get tasks (Role-based)
      responses:
        '200':
          description: List of tasks
        '401':
          description: Unauthorized - missing or invalid credentials
        '403':
          description: Forbidden - insufficient permissions
        '500':
          description: Server error

  /tasks/{id}:
    patch:
      tags:
        - Tasks
      summary: Update task (Technician only)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
      responses:
        '200':
          description: Task updated successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (Technician only)
        '404':
          description: Task not found
        '500':
          description: Server error

    delete:
      tags:
        - Tasks
      summary: Delete task (Manager only)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (Manager only)
        '404':
          description: Task not found
        '500':
          description: Server error
